Qa python homework 1
maximulicka/2020-2-Atom-QA-Python-M-Bogach pull request #1
Opened 2020-09-28 14:55 UTC by maximulicka

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
* Написать по 5 автотестов с учетом техних тест-дизайна на каждую из структур данных в Python:
* Проверить стиль кода линтером (pylint, flake8, pycodestyle).

2020-10-05 11:48 UTC, snicks92 requested changes
Работа хорошая, 1 мелкий коммент

2020-10-05 11:48 UTC, snicks92 commented on hw1/test_int.py
> +                assert x / y == result
кажется здесь лучше тогда сделать так, потому что деление на ноль никогда не будет эквивалентно эксепшену

```python
if y == 0:
    with pytest.raises(result):
        x / y
```

а еще лучше не привязываться на конкретное значение, а привязаться на тип result, если эксепшн - то заворачивать в ветку с pytest.raises, который будет ждать этот эксепшн:

```python
if issubclass(result, Exception)
    with pytest.raises(result):
        x / y
```

2020-10-05 21:00 UTC, maximulicka commented
> Работа хорошая, 1 мелкий коммент

Исправил замечание. Второй способ, который ты предложил сложнее реализовать, потому что для int происходит TypeError

2020-10-05 22:47 UTC, snicks92 requested changes
С последним коммитом влетел мусор hw1/__pycache__/test_int.cpython-37-pytest-6.1.0.pyc
Добавь .gitignore чтобы оно не летело больше.

Дополнительно заметил что изменен шаблон pull_request_template.md, давай вернем обратно и не будем его менять в коде, а менять только в окне создания ПР

2020-10-06 12:24 UTC, maximulicka commented
Все пофиксил

2020-10-06 12:54 UTC, snicks92 approved these changes

2020-10-06 12:54 UTC, snicks92 commented
Отлично, принято

2020-10-06 12:54 UTC, merged