Qa python homework 3
maximulicka/2020-2-Atom-QA-Python-M-Bogach pull request #3
Opened 2020-10-24 20:43 UTC by maximulicka

# Домашнее задание №3

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
#### Задача
* Тестирование портала https://target.my.com/
* Настроить окружение для запуска API тестов
* API тесты должны запускаться через марк -m API
 
    API (6 баллов):
     * Написать клиента, который будет иметь возможность авторизовываться (4 балла)
     * Написать тест на создание сегмента через API и проверку что сегмент создан (1 балл)
     * Написать тест на удаление сегмента через API (1 балл)

2020-10-26 22:28 UTC, snicks92 requested changes

2020-10-26 22:28 UTC, snicks92 commented on homework/hw3/code/tests/test_mytarget.py
> +        assert self.mytarget_client.delete_segment(segment) == 204
а если АПИ отдало 204 код, а сегмент на самом деле не удалился. надо либо запросить сегмент и убедиться что 404, либо запросить все и не найти в нем нужный

2020-10-27 21:18 UTC, maximulicka commented
Исправил

2020-10-28 14:54 UTC, merged

2020-10-28 14:54 UTC, snicks92 commented
Ок, принято. За сдачу после дедлайна оценка 4 из 6